### ISSUE TITLE
Polygon pads in footprints are not converted correctly

### ISSUE THREAD

**Issue by tianfeng33** [wokwi/easyeda2kicad#28]
Hi,  Just reporting on an issues with the conversion.  I seem to be missing pads and other things.  There is a link to the json file on the git hub.  
![unknown (1)](https://user-images.githubusercontent.com/42009022/76040827-6cf6e980-5f1e-11ea-962f-272b7d75d2d2.png)

![image](https://user-images.githubusercontent.com/42009022/76040819-68323580-5f1e-11ea-9a4c-3e7038a01f9e.png)

Here is a link to the project

https://easyeda.com/tianfeng/triple-bypass-v2

Thanks for your work

**Comment by urish** [comment]
Thanks for reporting!

Can you please also provide a list of the missing pads/other issues that you found so we can look into them?

**Comment by tianfeng33** [comment]
Sure there is a lot. 
I would start with it looks like the ground plane didn't convert. No GND pad
All pads are circular instead of square.
 r1-r4,r6,r22,c6,c7,c20 have no pads. 
 r,5,r7,r8,r10r,r18,r20,r27,r29,r30,r35,c4,c5,c12,c13, are missing the top pad. R11,r24,r25,r31,r31,r37,c3,c19 are missing the bottom.  
Several of the 0603 resistors pads also appear to be different sizes.

**Comment by urish** [comment]
Yes, I can definitely see these issues now. I attach the source JSON file for reference, and will start opening separate issues for each kind of problem shortly.

[issue-28.zip](https://github.com/wokwi/easyeda2kicad/files/4299273/issue-28.zip)

**Comment by urish** [comment]
Most of the issues (all the resistors related issues) seem to be related to conversion of polygon-shaped pads, so I renamed the issue to reflect that.

**Comment by urish** [comment]
Hi @tianfeng33, can you please check again with the last version from master?

Most issues should be resolved now, except for the GND PAD, which should eventually be fixed once #26 will be done and merged.

**Comment by rattboi** [comment]
I just tried this via the new online converter and it looks to be the same as before. Will the online version track specific releases or HEAD?

**Comment by urish** [comment]
@rattboi the online version tracks the releases. I have just released the latest fixes as 1.7.0, so they should now be reflected there as well.

**Comment by tianfeng33** [comment]
I took some time with this today and noticed an issue but I don;t know what is causing it.  The problematic pads are converting as custom circular and not rectangle.  They need to be rotated 180 and changed to rectangle to make them match the correct ones.  I am still experiencing issues with some ground pads not attaching to the ground flood even though the net is gnd.

**Comment by urish** [comment]
Hi @tianfeng33, have you used the latest version (1.7.0)? If yes, can you please attach a screenshot highlighting the issues?

**Comment by tianfeng33** [comment]
![image](https://user-images.githubusercontent.com/42009022/76907331-56d11d80-687c-11ea-9065-9aac48f094e7.png)  the non labeled pad is normal

![image](https://user-images.githubusercontent.com/42009022/76907377-70726500-687c-11ea-9a1e-5690263952b6.png)

Then changed to this.
![image](https://user-images.githubusercontent.com/42009022/76907411-87b15280-687c-11ea-8abe-e86833ac2d60.png)
 
The GND issue might be related to my lack of familiarity with Kicad but everything circled in red is gnd net.  
![image](https://user-images.githubusercontent.com/42009022/76907616-07d7b800-687d-11ea-89e9-21589632b97b.png)
 but only some of them are reading that attachment and creating a spoke to ground on a fill.

**Comment by urish** [comment]
So here is the deal - it seems like these pads are defined as having a custom shape (polygon) in EasyEDA, and as such, we also convert them to custom shape pads in KiCad. It seems like KiCad can't connect pads with custom shape to the ground fill. I will see if we can automatically detect from the list of points that this looks like a rectangle, and emit a rectangle pad instead of a custom-shape pad.

**Comment by urish** [comment]
Can you please check now, with version 1.7.1?

**Comment by tianfeng33** [comment]
I checked the other day and forgot to update you.  It is all working much better.  Only one small issues left.  The ground fill does not attach to the two pins on the tssop 14 footprint.  I just connected them with traces.  It is a very small thing but I thought I would mention it

**Comment by urish** [comment]
Thanks for the update @tianfeng33! The same happens on my end. The reason for this seems to be the minimum width of the Copper Zone, which is set to 0.254mm. 

![image](https://user-images.githubusercontent.com/892318/77845522-34ae9800-71b8-11ea-9347-498f29cafdbe.png)

I tried changing it to 0.1mm, and it did the trick for all 3 pads:

![image](https://user-images.githubusercontent.com/892318/77845557-72abbc00-71b8-11ea-8c3f-a40c46fa325d.png)
